name: ApexGrid CI/CD Pipeline

# Corre sempre que fazes Push para a branch main
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    name: Build & Test (Android)
    runs-on: ubuntu-latest

    steps:
      # 1. Faz o clone do teu repositório (Atualizado para v4)
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Prepara o Java (Atualizado para v4)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. Instala o SDK do Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x' 
          channel: 'stable'

      # 4. Descarrega pacotes
      - name: Install Dependencies
        run: flutter pub get

      # 5. Corre a análise de código à procura de erros
      - name: Analyze Code
        run: flutter analyze

      # 6. Corre os teus testes 
      - name: Run Tests
        run: flutter test

      # 7. Compila a aplicação para Android
      - name: Build APK
        run: flutter build apk --release

      # 8. Guarda o APK gerado nos Artifacts (A GRANDE CORREÇÃO: v4)
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ApexGrid-Release-APK
          path: build/app/outputs/flutter-apk/app-release.apk